### ISSUE TITLE
AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by zgtibu** [athulaugustine/WhatsApp-Auto-Message#1]
Error coming while uploading excel

**Comment by zgtibu** [comment]
When sending messages, if the number is not on WhatsApp, it gets added to the previous number, and the message is sent to the previous number instead because the chat screen remains the same.

**Comment by athulaugustine** [comment]
Fixed the issue. The excel should have columns -  ['Customer ID', 'Customer Name', 'Contact No.']
